In [38]:
#Import libraries
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.preprocessing import scale
import matplotlib.pyplot as plt
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import KMeans
import scipy.cluster.hierarchy as sch
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score as sil

In [39]:
pca=PCA()

In [40]:
ls

 Volume in drive C is ssd
 Volume Serial Number is 344C-651C

 Directory of C:\Users\phoneclicker\Downloads\excelr_kd\ASSIGNMENT\pca

12/29/2022  03:53 PM    <DIR>          .
12/29/2022  03:53 PM    <DIR>          ..
12/28/2022  11:19 PM    <DIR>          .ipynb_checkpoints
12/29/2022  03:53 PM            24,851 pca.ipynb
11/29/2022  03:33 PM               368 PCA_problem Statement.txt
11/29/2022  03:33 PM            11,425 wine.csv
               3 File(s)         36,644 bytes
               3 Dir(s)  23,858,696,192 bytes free


In [41]:
wine=pd.read_csv("wine.csv")

In [42]:
wine.head()

Type  Alcohol  Malic   Ash  Alcalinity  Magnesium  Phenols  Flavanoids  \
0     1    14.23   1.71  2.43        15.6        127     2.80        3.06   
1     1    13.20   1.78  2.14        11.2        100     2.65        2.76   
2     1    13.16   2.36  2.67        18.6        101     2.80        3.24   
3     1    14.37   1.95  2.50        16.8        113     3.85        3.49   
4     1    13.24   2.59  2.87        21.0        118     2.80        2.69   

   Nonflavanoids  Proanthocyanins  Color   Hue  Dilution  Proline  
0           0.28             2.29   5.64  1.04      3.92     1065  
1           0.26             1.28   4.38  1.05      3.40     1050  
2           0.30             2.81   5.68  1.03      3.17     1185  
3           0.24             2.18   7.80  0.86      3.45     1480  
4           0.39             1.82   4.32  1.04      2.93      735

In [49]:
wine=wine.iloc[:,1:]


In [50]:
wine

Alcalinity  Magnesium  Phenols  Flavanoids  Nonflavanoids  \
0          15.6        127     2.80        3.06           0.28   
1          11.2        100     2.65        2.76           0.26   
2          18.6        101     2.80        3.24           0.30   
3          16.8        113     3.85        3.49           0.24   
4          21.0        118     2.80        2.69           0.39   
..          ...        ...      ...         ...            ...   
173        20.5         95     1.68        0.61           0.52   
174        23.0        102     1.80        0.75           0.43   
175        20.0        120     1.59        0.69           0.43   
176        20.0        120     1.65        0.68           0.53   
177        24.5         96     2.05        0.76           0.56   

     Proanthocyanins  Color   Hue  Dilution  Proline  
0               2.29   5.64  1.04      3.92     1065  
1               1.28   4.38  1.05      3.40     1050  
2               2.81   5.68  1.03      3.17     1185  
3               2.18   7.80  0.86      3.45     1480  
4               1.82   4.32  1.04      2.93      735  
..               ...    ...   ...       ...      ...  
173             1.06   7.70  0.64      1.74      740  
174             1.41   7.30  0.70      1.56      750  
175             1.35  10.20  0.59      1.56      835  
176             1.46   9.30  0.60      1.62      840  
177             1.35   9.20  0.61      1.60      560  

[178 rows x 10 columns]

In [48]:
pca.fit(wine).components_

array([[ 1.94906240e-04, -4.67130166e-03,  1.78680352e-02,
         9.89830391e-04,  1.56728950e-03, -1.23086713e-04,
         6.00608659e-04,  2.32714165e-03,  1.71380103e-04,
         7.04932341e-04,  9.99824545e-01],
       [ 4.59280097e-03,  2.64410184e-02,  9.99347723e-01,
         8.80235327e-04, -4.68538116e-05, -1.35494213e-03,
         5.00598859e-03,  1.50854434e-02, -7.60704633e-04,
        -3.49169915e-03, -1.77733654e-02],
       [-5.23539653e-02, -9.51814714e-01,  2.96116866e-02,
         3.82175156e-02,  8.05659133e-02, -1.32317741e-02,
         2.31594664e-02, -2.77017430e-01,  2.41135510e-02,
         6.65374716e-02, -4.55192646e-03],
       [ 8.67172341e-03,  2.99027455e-01,  6.25662570e-03,
         7.58948585e-02,  1.71946575e-01, -1.12806376e-02,
         5.02860654e-02, -9.13686404e-01,  6.01857719e-02,
         1.84480614e-01,  2.89358421e-03],
       [ 3.63699873e-02,  2.99837465e-02, -5.92897280e-03,
         4.22199958e-01,  6.90154335e-01, -3.77596795e-02,
  

In [16]:
wine1=wine.iloc[:,0:]

# Hierarchical 

In [17]:
winenorm=scale(wine1)

In [18]:
winenorm

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [20]:
var=pca.explained_variance_ratio_

In [23]:
var

array([9.98091230e-01, 1.73591562e-03, 9.49589576e-05, 5.02173562e-05,
       1.23636847e-05, 8.46213034e-06, 2.80681456e-06, 1.52308053e-06,
       1.12783044e-06, 7.21415811e-07, 3.78060267e-07, 2.12013755e-07,
       8.25392788e-08])

In [24]:
len(var)

13

In [27]:
#plt.bar(range(1,len(var)+1),var)
plt.bar(range(1,len(Var)+1),Var)

NameError: name 'Var' is not defined